### ISSUE TITLE
Drawing show page needs to have more info

### ISSUE THREAD

**Issue by steverabino** [empowerhack/DrawMyLife-Service#103]
There is information missing from the Drawing Show page

All artist information; gender, age, story

Story is quite important especially as it gets trimmed on the Manage Drawings page, but obviously, it would be good for this view to have all the info shown.

The information that is currently there is also pretty much just dumped there, it'd be good to get this prettified at the same time.

![image](https://cloud.githubusercontent.com/assets/4599695/18033076/b1f17d96-6d11-11e6-85f3-7f9c19e4a7da.png)

**Comment by krissy** [comment]
Addressed in #103
