### ISSUE TITLE
Website not responsive for mobile or tablet

### ISSUE THREAD

**Issue by EChesters** [empowerhack/DrawMyLife-Service#106]
There's a meta line missing from the head tag which Bootstrap needs when responding to non-desktop devices:

`<meta name="viewport" content="width=device-width, initial-scale=1">` needs to be in the `head` of each document. 

**Screenshot of issue on mobile**
Despite the screenshot being huge, the fields are tiny on the screen.
![screenshot_20160831-163201](https://cloud.githubusercontent.com/assets/2605703/18135128/b50fd21e-6f98-11e6-822d-7f287df1ee94.png)

To explain it a bit better is the Bootstrap documentation: http://getbootstrap.com/css/#overview

**Comment by krissy** [comment]
We had an issue to address responsiveness around the site (#54) which was closed, perhaps to not be lost in pilot tasks. This can be our new "make the site responsive" issue. 

Current status is the form page has been made navigable on a mobile, but there are other elements that need updating with bootstrap classes etc in order for this meta element to be applied and not break the layout. 

One for @tanyapowell to address as a priority task for the next phase once we regroup.

**Comment by tanyapowell** [comment]
I'll add this to the head now 👯 @EChesters and @krissy
