### ISSUE TITLE
Confirm need for recording artist's Stage of Journey

### ISSUE THREAD

**Issue by krissy** [empowerhack/DrawMyLife-Service#111]
# What

Confirm the need for an additional `journey_stage` field to determine the artist's stage in the migration journey.
# How

Discuss with team and implement if agreed upon.
# Considerations

One important insight this project aims to analyse is the patterns of mental health of artists at different stages of the migration journey. Currently, we have a Subject Matter field that contains values such as "Camp life", but this is linked to the content of the drawings rather than the artist's stage when creating the drawing. Is this is an important piece of the data that's missing right now?

**Comment by CathMollie** [comment]
I think this _is_ important data and we should capture it. I know that Camille was very interested in the link between journey stage and state of mind too. We'll have to make sure the difference between this and subject matter field is very clear to field workers.

We could talk to Tdh about the actual values to go with this field e.g. new arrival, awaiting transit, etc

Also, the more data we collect which could potentially identify artist and their location, the more important consent becomes. 

**If picking this up at WHFNP hack night**
We need a brand new field with drop-down options called Stage of Journey. This is to capture the situation the child is in, i.e. have they recently arrived

Values are:
- At home
- In temporary shelter
- Awaiting transit
- On the move
- Arrived at destination

[And any others you can think of]

<img width="1250" alt="screen shot 2016-10-06 at 19 57 28" src="https://cloud.githubusercontent.com/assets/20586372/19166461/7ec047e2-8bff-11e6-8a13-6a753b59a332.png">

**Comment by mathildathompson** [comment]
@CathMollie I have just started working on this ticket. Do you want the field to be optional or required? :-)

**Comment by krissy** [comment]
@mathildathompson Good Q - Let's make it optional as we might not always know this. And the field will default to Not Known. cc @CathMollie

**Comment by steverabino** [comment]
Done!
