### ISSUE TITLE
Update Drawing field: Mood rating

### ISSUE THREAD

**Issue by CathMollie** [empowerhack/DrawMyLife-Service#113]
## What

The Mood Rating meter ranges from 1-10 right now. From pilot feedback, this is too broad a range and confusing as to what to select. We need to simplify this rating scale down to 1-5. (short-term solution)

<img width="725" alt="screen shot 2016-10-06 at 19 51 55" src="https://cloud.githubusercontent.com/assets/20586372/19166159/6d956aac-8bfe-11e6-9c59-6d79131199a8.png">
## How

Update the drawing form field and model validations so this is limited to between 1 and 5.
We also need to backfill any existing data to an appropriate number within the new range.
We also need to more clearly define purpose of scale - (1) Image reflects child's mood; or (2) Image contains sensitive or disturbing material - i.e. warning to those viewing it.
## Todo

Implement the above.
Confirm copy from @CathMollie re purpose of scale.

**Comment by tanyapowell** [comment]
@CathMollie just to confirm this task is _actually_ to achieve the short term goal? i.e.

> Short-term - Reduce scale e.g. 1-5 not 1-10 OR go for more 'emotive' or symbolic indicators of mood. Feel free to play with ideas!

and the long term goal will be a separate task?

**Comment by CathMollie** [comment]
@tanyapowell Yes, the long term goal will be separate as we may go for something quite different to a numeric scale. But in the short term our piloters said that having fewer numbers to pick from would help. I need to talk to @smurfyrach and @dama about the 'data' side of this - i.e. do we need to stick with numeric values because it makes data analysis easier. Will raise with them on Design Day.

**Comment by krissy** [comment]
@tanyapowell Are you taking this on? This is open for re-assignment if so.

**Comment by tanyapowell** [comment]
@krissy somebody else was assigned to this, but I can do this quickly if no one else is doing it?

**Comment by tanyapowell** [comment]
Frontend work completed and merged #129

**Comment by krissy** [comment]
Backend completed in https://github.com/empowerhack/DrawMyLife-Service/pull/134
