### ISSUE TITLE
New Drawing field/s: Consent

### ISSUE THREAD

**Issue by krissy** [empowerhack/DrawMyLife-Service#123]
## What

We need to add a new field to Drawings to mark consent from the artist for the ability to use their drawing for our specific contexts.
## How

TBC. We are confirming what tiers of consent we need, which will affect whether this is a single-value field or multi-selection.
## Considerations
- Some suggestions made in https://github.com/empowerhack/DrawMyLife-Service/issues/83 for reference  (need confirmation)
## To Do

Dama + @smurfyrach to confirm consent requirements.

**Comment by CathMollie** [comment]
Following call with @smurfyrach 19 Oct:
- Confirming consent requirements in #83 are OK.
- Mandatory fields.
- If consent to share data not given, can we ensure that this data set is never published/output from API?

**Comment by krissy** [comment]
:+1: Feedback looks good - moving this back to Pick Me Up

**Comment by tanyapowell** [comment]
@CathMollie is it only one consent box that needs ticking? Also, who is writing the copy for the consent label? Could you send me the link on Slack where all the consent stuff is pretty please? Muchos x

**Comment by CathMollie** [comment]
@tanyapowell I don't think we have copy so I'll ask @smurfyrach to confirm via Slack.

**Comment by CathMollie** [comment]
To make consistent with EULA (End User Licence Agreement as drafted by @smurfyrach )

Use the following copy:
[Tickbox to indicate consent from child to collect artwork] Consent given by artist to DrawMyLife and partners to collect artwork.
['Yes/No' option to indicate consent from child to showcase artwork] Consent given by artist to share data on open source data platforms as deemed appropriate.

We will need to use the pilot to ensure that this copy is understood by field workers, especially those who don't have English as a first language.

**Comment by steverabino** [comment]
#133 has gone live with the following agreed rules:
1. There will only be one consent box on drawings:
   - **Consent given by artist to share image on open source data platforms as deemed appropriate**
2. For any existing drawings, this will be false, unless someone goes back in to edit the drawing and change it
3. We will not ask for permission to collect data, but that will go into user guide/terms that verbal consent to collect is assumed by default if user is uploading the image and data.
