### ISSUE TITLE
Tests: Add more model specs

### ISSUE THREAD

**Issue by krissy** [empowerhack/DrawMyLife-Service#126]
## What

We need to add more model tests. Some have already been created but time constraints have prevented full coverage.
## How

Add more model specs (+ feel free to improve existing ones)  covering all current methods, similar to tests living here: https://github.com/empowerhack/DrawMyLife-Service/blob/master/spec/models
## To Do

Pick me up! Good rspec practice.

**Comment by hannako** [comment]
@krissy I'm just working on specs for the user model at the moment. This test fails, is that what you would expect?
