### ISSUE TITLE
Choose a branding palette

### ISSUE THREAD

**Issue by EChesters** [empowerhack/DrawMyLife-Service#132]
## What
We need to finish the branding palette slides on Google Drive:
https://drive.google.com/drive/folders/0B0VW1uB8P8sdUGFDc3c5dzdDc1U

When we are ready we need to vote on each slide, and decide on a slide. (Mix & Match of slides is allowed)

## How
We need everyone to have a look before we get ready to vote. 
**I think a deadline when we should vote would be a good idea.**

## Considerations
Do not change slides - create your own and take things from slides
The branding word cloud is also in that folder, that we did on the Design Day for tone/considerations.

## To Do
* Add to the slides in the branding folder [Link above]

**Comment by rocioleon** [comment]
Issue moved to [empowerhack/DrawMyLife-Website #46](https://github.com/empowerhack/DrawMyLife-Website/issues/46) via [**ZenHub**](https://www.zenhub.com/)
