### ISSUE TITLE
Drawing form: Add Country of Origin field

### ISSUE THREAD

**Issue by krissy** [empowerhack/DrawMyLife-Service#141]
## What
Destination Unknown are interested in collecting the child artist's nationality, for the 'Drawings' interface of the DML Campaign Tool. 

## Considerations
* This should be presented as *Country of Origin* with a drop-down list of countries. See example here ('Origin' section) http://popstats.unhcr.org/en/asylum_seekers
* This is another data field in a form that is already long and will add further time to fieldworker upload. The new field would sit below 'Age of artist' in the *Details of artist* section. Confirm with team whether we want to add this now.
@EChesters @rocioleon @tanyapowell

**Comment by steverabino** [comment]
Addressed by #151
