### ISSUE TITLE
❤️ UX love for signup pages

### ISSUE THREAD

**Issue by steverabino** [empowerhack/DrawMyLife-Service#142]
## What
Although PR #139 Standardises the style of the signup pages, they could really do with having a nicer standardised style, maybe in-keeping with a brand 

![image](https://cloud.githubusercontent.com/assets/4599695/21964163/c3de6000-db3e-11e6-8219-77ad9ebcd054.png)

**Comment by CathMollie** [comment]
It'd be awesome if we could have this ready by end Jan if possible @marizoldi. Next pilot likely to begin in Feb and sign-up process might feature in the User Guide we're making for it.

**Comment by marizoldi** [comment]
No problem @CathMollie. Is that a stand alone or follows @EChesters 's designs?

**Comment by CathMollie** [comment]
Standalone. It's separate from the DML Website @EChesters is working on - different users etc. That said if we have a DML style library (ask @EChesters ) you could always take from that. But main thing here is that it needs to be simple, elegant, intuitive. I guess there may also be potential in future for translating these pages too - but not yet.

**Comment by CathMollie** [comment]
This is totally separate to the DML Website but if we have a DML style guide we could definitely take from that. And DML logo. See #139 for the complete set of pages.

**Comment by CathMollie** [comment]
Designs look great.
On #2 and #3, thought the white-on-red error text was quite small and tucked-away.

**Comment by EChesters** [comment]
Wasn't sure where to put feedback as I can't annotate PDFs, but left it on our drive. (See Slack too)

General issues were: 
- labels need to be placed outside of fields
- white text on yellow background is hard to read + a thin font
- language needs to be less formal
- errors need to include information to resolve issue

**Comment by CathMollie** [comment]
Styling dependent on branding. With @rocioleon.

**Comment by marizoldi** [comment]
@EChesters responses to your review in the document.
