### ISSUE TITLE
Confirm HXL dataset design for HDX integration (first iteration)

### ISSUE THREAD

**Issue by krissy** [empowerhack/DrawMyLife-Service#146]
Blocks: #145, #147 

## What

We want to finalize the data design for our first iteration of an open [HXL-formatted](hxlstandard.org) dataset to share with the [Humanitarian Data Exchange (HDX)](data.humdata.org), helping visualise the *"Number of displaced children and their conveyed moods in art therapy"*. 

We have been collaborating with HDX staff with this [Google Spreadsheet](https://docs.google.com/spreadsheets/d/16QoGsMemHqERynI5XFYQsYGKXXJFxvhmiLj0jsNKmYw/edit#gid=2141927409) and are almost there. We need to lock in what our first version of this dataset is and confirm when we can unblock our internal data tasks in #145 and #147.

## Pending Confirmation

- [x] For Mood Ratings we collect a numeric scale between 1-5. The spreadsheet currently displays these as the labels `NEGATIVE`, `POSITIVE` and `NEUTRAL`, i.e. 1-2, 4-5, and 3 respectively. Is this valid?
- [x] Spreadsheet currently has a suggested "region" column, but we don't currently collect location data at this level. We can stick with country only for now but should confirm if we want to add this to our form for next pilot.
- [x] Confirm all columns
- [x] Confirm all HXL hashtags

## How

Finalize data design with team and HDX, including confirming any custom data tags we need. When this is done, update the ticket in #145 and start progress on it.

**Comment by CathMollie** [comment]
Call with HDX scheduled (9/2 TBC) so we can confirm all of the above. @marizoldi

**Comment by CathMollie** [comment]
@krissy If you are happy with changes to hashtags, this issue can now close. 

- 'Mood' is now expressed as impact + indicator + code. Values need updating.
- Custom hashtags created for stages of journey, as advised by HDX.
https://docs.google.com/spreadsheets/d/16QoGsMemHqERynI5XFYQsYGKXXJFxvhmiLj0jsNKmYw/edit#gid=2141927409
- We will represent nationality as Country of Origin - no plans to add Region yet.

**Still to do:**
Update actual values in Mood now that we are expressing data differently.

**What's next:**
Mariza has opened #148 to take forward data modelling, based on these hashtags

**Comment by krissy** [comment]
@CathMollie @marizoldi awesome! Yep, if you're all happy and have cross-checked with the team at HXL's end then :+1: from me! This is the first iteration in any case so if we find anything new when picking up the dependent tickets then things are flexible and we can revisit.
