### ISSUE TITLE
Research: Art Therapy with child soldiers, contact Margaret @ QMU

### ISSUE THREAD

**Issue by krissy** [empowerhack/DrawMyLife-Service#175]
## What

To improve our process and data and ensure relevancy, contact Dr Margaret Hills de Zarate (MHills@qmu.ac.uk), Senior Lecturer & Programme Leader Art Therapy at Queen Margaret University, who has lots of experience working abroad with child soldiers. (see CV at http://www.qmu.ac.uk/otat/M_Hills%20de%20Zarate.htm)

Referred by Georgina Ruth from With Kids.

## How

- Collate findings, learnings and actions in our protected [rollings meetings Google document](https://docs.google.com/a/designswinger.com/document/d/1RCGUeC0x8_I3CCEH7xTCvbRO1UAm4iBFHDDEzNi9zoY/edit?usp=sharing), _not_ on GitHub
- Explain the [DML initiative](https://github.com/empowerhack/DrawMyLife-Service/wiki/1.-Project-Definition) and that you were referred by Georgina. Feel free to share link to drawmylife.org.
- Explain what we're currently collecting in form, that we've previously piloted in a humanitarian day centre in Novi Sad, Serbia (http://www.nshc.org.rs/)
- Gather open insights about her experience of art therapy in general
- Gather open insights about her experience of art therapy working with child soldiers
- Ask for advice on how DML data could be effective campaigning for funding for refugee children's mental health support
- Ask for advice on our data fields / what we're collecting
- Ask for advice on how we're collecting it, any legalities, any software used to collate this type of data
- Ask about insights on the Leuven Scale and SDQ in measuring impact (see and add notes to issue #179)
- Ask for any additional references / contacts
- Share learnings in document with DML team and decide on next steps

**Comment by marizoldi** [comment]
Done. Document with notes on Google drive..
