### ISSUE TITLE
User Roles

### ISSUE THREAD

**Issue by steverabino** [empowerhack/DrawMyLife-Service#22]
While creating issues, it's become apparent to me that most users are going to be interested in seeing their own organisation's information. If the app gains traction and starts being used by several organisations, seeing all drawings from all organisations/locations is going to get messy.

However, some users are going to need to be admins to be able to:
1. Manage users from all organisation
2. Keep an eye on submissions from all organisations/locations to spot misuse, and ensure a certain standard of data entry is being met.
3. Have ability to edit/delete any drawings from any orgs/location

---
1. `superuser`
   - access to all
   - plus access to add new organisations
2. Organisation Admin (just name `admin`?)
   - can edit own organisation
   - can view/add/edit/make inactive users of organisation
   - can view/add/edit/delete drawings of own organisation only
   - Should we allow an existing Organisation Admin to be able to create another organisation? (currently, each user belongs to only one org, so they'd need to create a new admin user for that new org - sounds messy)
3. Organisation User (just name `user`?)
   - can edit own user profile
   - can view/add/edit/delete own drawings
   - can view/add/edit/delete drawings of own organisation only?

**Comment by krissy** [comment]
Moved to wiki: https://github.com/empowerhack/DrawMyLife-Service/wiki/2.1-Org-structure-and-roles
