### ISSUE TITLE
Use Jbuilder

### ISSUE THREAD

**Issue by HisashiQ** [empowerhack/DrawMyLife-Service#24]
You'll need to dig deep when you start figuring out what end points to expose and creating conditons for the json API endpoints.
Jbuilder comes complied with your gemfile when you first create a "rails new [project name]" (It's already bundled from what I can see in your gemfile).
It lets you keep your controllers clean and write really short code.
**Example:**
- Delete any json formatting from show and just create an instance variable such as `@drawings = Drawing.all`
- Create a corresponding .json.jbuilder file in view directory
  (in this case show.erb.html would also have a show.json.jbuilder file)
- Write `json.(@drawing, :id, :name)` etc.
- You can even set if admin? and render certain endpoints if admin to create secure endpoints in your jbuilder file).

**Comment by krissy** [comment]
:+1: Thanks @HisashiQ - will consider once ball is rolling with build. :)

**Comment by steverabino** [comment]
Using ActiverRecord serialisers
