### ISSUE TITLE
Add country data to drawings during upload

### ISSUE THREAD

**Issue by CathMollie** [empowerhack/DrawMyLife-Service#31]
Find best way of doing this.

Also raised by @rocioleon in wireframes

**Comment by steverabino** [comment]
Picking this up now...

**Comment by stevesmith2609** [comment]
1. Add country to user
2. Add country to drawing, and default on `new` drawing to user's country

**Comment by stevesmith2609** [comment]
[ ] Remove model for locations and references to model
[ ] Add country gem
[ ] Add country to User model
[ ] Add country to New/Edit User views
[ ] Add country to Drawing Model
[ ] Add country to New/Edit Drawing views
[ ] Add country to Show Drawing view (and possibly Index Drawing view)
[ ] Default country to User's country on `New` Drawing view

**Comment by steverabino** [comment]
Fixed with https://github.com/empowerhack/DrawMyLife-Service/issues/38
