### ISSUE TITLE
Expose all form fields once confirmed

### ISSUE THREAD

**Issue by CathMollie** [empowerhack/DrawMyLife-Service#33]
See also questions in @rocioleon 's wireframes (being reviewed by @krissy )
Confirmed data fields are:
1. Age
2. Gender
3. Journey stage (home, transit, camplife, future aspirations)
4. Story
5. Mood rating (positive, sad, funny - use slider) - REMOVE IF DOESN'T WORK ON SUBMIT FORM
6. Description
7. Country drawing was collected in (user will pick from list)

**Comment by krissy** [comment]
Renamed this as this was more for what fields to show in the form. Will make a separate task for what data to expose in the API and defining the endpoints.

**Comment by krissy** [comment]
It's also done, as we already show these form fields
