### ISSUE TITLE
Create style guide once wireframes complete

### ISSUE THREAD

**Issue by CathMollie** [empowerhack/DrawMyLife-Service#34]
Same guide will be used for campaigning tool

**Comment by rocioleon** [comment]
Hi,
So far...
The idea I have in mind about the look and feel for both Portal and web are going to follow the website of Terre des hommes as they are supporting this project some how. 

@tanyapowell 
Based on this I've downloaded and attached in here the font family Universal which also have a web version. Also you could some how reuse the code from the online style guide 'yelp' (I don't know if this is useful for you but in case). 
Create the base grid 12 columns. There is an open resource on Github where you can get the code for this (attached file)

![style_guide_inprocess](https://cloud.githubusercontent.com/assets/18365496/17525253/cf83be62-5e59-11e6-9da8-9aeaa1aee242.jpg)

[universltstdxblackex.zip](https://github.com/empowerhack/DrawMyLife-Service/files/409480/universltstdxblackex.zip)
[responsivegridsystem.zip](https://github.com/empowerhack/DrawMyLife-Service/files/409481/responsivegridsystem.zip)
[ResponsiveGridSystem_notes.txt](https://github.com/empowerhack/DrawMyLife-Service/files/409483/ResponsiveGridSystem_notes.txt)

**Comment by rocioleon** [comment]
As you can see it is not complete but there is a point starting. 
Let me know any questions

Rocio

**Comment by rocioleon** [comment]
@EChesters @CathMollie @tanyapowell @krissy 

I think we can leave this card for the Design sprint on 8th October. In addition, I would like to hear your thoughts about the Draw My Life identity + Terre Des Hommes ?? (I guess this issue still in discussion with Camille)

**Comment by steverabino** [comment]
Closing as we have this now branding being considered separately
