### ISSUE TITLE
Build UI based on agreed styles

### ISSUE THREAD

**Issue by CathMollie** [empowerhack/DrawMyLife-Service#35]
Work on this w/c 8 Aug once wireframes complete and style guide ready.

@tanyapowell Break this into smaller tasks if helpful!

**Comment by tanyapowell** [comment]
@CathMollie yep, will break into smaller tasks so it's easier to digest and in case others want to pick up tasks

**Comment by CathMollie** [comment]
@tanyapowell Great - I'll now close this place holder
