### ISSUE TITLE
Create Business Rules Doc

### ISSUE THREAD

**Issue by CathMollie** [empowerhack/DrawMyLife-Service#41]
- Find template and share with team 
- Store on GH?
- Can already add rules re: country

**Comment by CathMollie** [comment]
Create Google sheet. 
- Give each rule an ID and description
- Give each one a status - e.g. more info needed from Camille

**Comment by krissy** [comment]
Hey @CathMollie, I've not seen business rules in a sheet before so not sure how convenient it is to maintain etc. I imagined them living in a section in this repo's [wiki](https://github.com/empowerhack/DrawMyLife-Service/wiki) which anyone can edit and also find easily. But will leave it to you to set up what works best!

**Comment by CathMollie** [comment]
@krissy agree wiki a good central location. I'll make a start (using the rules we've captured in our issues already)

**Comment by CathMollie** [comment]
Add info from #22

**Comment by krissy** [comment]
Done in wiki
