### ISSUE TITLE
Define use cases for login and access 

### ISSUE THREAD

**Issue by CathMollie** [empowerhack/DrawMyLife-Service#44]
Considerations below. 

First step is to establish some general principles with Camille
Then write use cases & workflow - is anyone skilled at process flows in team?

To consider:
- Do they want one general organisation login vs individual login? 
- Do we need privilege levels for different users? E.g. some users can only view, some can edit. are we happy just having a user@terredeshommes.org login that everyone in the org can use? 
- Do we need to monitor who is uploading what? ATM users can only edit/delete images they originally uploaded - we probably need to change this post-pilot so anyone within the org can edit other’s uploads?

**Comment by krissy** [comment]
We are going to follow the use cases listed on our wiki https://github.com/empowerhack/DrawMyLife-Service/wiki/2.1-Org-structure-and-roles and let's keep that up-to-date if spec changes.
