### ISSUE TITLE
Ensure Mandatory/Optional of pictures fields are validated correctly

### ISSUE THREAD

**Issue by steverabino** [empowerhack/DrawMyLife-Service#49]
| Data Point | When Incomplete | When Complete | Why? |
| --- | --- | --- | --- |
| Image file | MANDATORY | MANDATORY |  |
| Description of drawing | Optional | MANDATORY | Should always be able to describe the picture |
| Subject Matter of drawing (Home/In Transit/In Camp/Future) | Optional | MANDATORY | Should always be able to describe the picture |
| Mood rating of drawing (1 to 10) | Optional | MANDATORY | Should always be able to describe the picture |
| Country picture was drawn | Optional | MANDATORY | Though it is possible that this information will not be available, Kris and I think it's important for this to be recorded as best as can be remembered, rather than possibly missing out on the data in future |
| Age of child | Optional | Optional | Older pictures will not have corresponding child data available |
| Gender of child | Optional | Optional | Older pictures will not have corresponding child data available |
| Story of child / psychological notes | Optional | Optional | Older pictures will not have corresponding child data available |
| Status (Pending / Complete) | MANDATORY | MANDATORY | Will always have a status |

@rocioleon @tanyapowell @krissy  - do you have any comments on these? ☝️

**Comment by steverabino** [comment]
Very much related to changes in #39

**Comment by krissy** [comment]
Rules make sense :+1: happy to pick this up next, unless you're awaiting more thumbs

**Comment by rocioleon** [comment]
It looks perfect, thanks @stevesmith2609

**Comment by steverabino** [comment]
Kris fixed this in #55
