### ISSUE TITLE
Portal API wireframe 

### ISSUE THREAD

**Issue by rocioleon** [empowerhack/DrawMyLife-Service#50]
Wireframe_v2 after meeting with Krissy:
- Content Management section (home page / file list view)
- Organisation (awaiting for more information from the user)
- Settings (awaiting for more information from the user)
- Upload new file (button)
- User profile (awaiting for more information from the user)

**Comment by rocioleon** [comment]
@tanyapowell 

There are some yellow notes on the wireframe to guide you. Let me know if there is something not clear.

@krissy 
Just a double check is always good.

**Comment by rocioleon** [comment]
[DML_portal_wireframe_v2.pdf](https://github.com/empowerhack/DrawMyLife-Service/files/405591/DML_portal_wireframe_v2.pdf)

**Comment by rocioleon** [comment]
@tanyapowell 
I will be working on the style guide this week but as a starting point my idea is to use Font Awesome and Flat icon resources as it would be easier and quicker for both of us. I think you know about this already, but in case
https://github.com/empowerhack/templates/blob/master/README.md

**Comment by tanyapowell** [comment]
@rocioleon have created an issue for Font Awesome to be added to the project. The issue can be found here #60 

Quick question - after the user logs in is the next thing they see page 1 of the wireframes?

**Comment by rocioleon** [comment]
@tanyapowell 
Yes, as soon as they are logged in, Content Management works as landing page as well. Does it make sense or did I miss anything?

**Comment by tanyapowell** [comment]
@rocioleon makes sense! Just double checking 😄

**Comment by tanyapowell** [comment]
@rocioleon just saw this note you wrote to @krissy regarding the description column on page 1 
![image](https://cloud.githubusercontent.com/assets/11095605/17535642/cc2ef0e6-5e87-11e6-881c-f9871312e457.png)

I've restricted this column to 30 characters (see below for an example). Let me know if you want to increase or reduce the number
![image](https://cloud.githubusercontent.com/assets/11095605/17535694/0c7e81d4-5e88-11e6-8c00-b03692285507.png)

**Comment by rocioleon** [comment]
Yes, it looks good to me

**Comment by tanyapowell** [comment]
@rocioleon when you have a chance can we have something for the footer? Can't see it in any of the wireframes. Thanks 😄

**Comment by rocioleon** [comment]
@tanyapowell I haven't been working on the wireframe during these last days as you can see. I am aware that the wireframe are not 100% finished and correct. I can see that there is pagination missing and some potential issues with navigation but I thought there were good enough to start with. Also regarding the mobile design, this is going to be done during the next milestone so I will work on this properly during the time schedule for it. Although you said already the solution I have in mind which is 'click' on the thumbnail and it will open the pop-up and closed by touching other part of the screen :)

I will have a call with Cath and Han to prepare the usability test and agreed a couple of things that needs to be done based on what we've got already. After this call I will focus on your requests and let you know. It is being tough week for me and i was not focused 100%. 

Please, next time if you see that I don't reply to your messages (within 24 hours) on this channel, let me know on a private message on slack to grab my attention to the specific issue so I will not keep you waiting again. I don't like keeping people waiting for me. Apologies!!
