### ISSUE TITLE
Change "Deleting Users" to "Making users inactive"

### ISSUE THREAD

**Issue by steverabino** [empowerhack/DrawMyLife-Service#53]
Currently, if a user is deleted, their drawing are also deleted from the system and we lose all record of them.
- [ ] Make it so users can be made inactive
- [ ] Remove the dependency on deleting drawing if a user _does_ happen to be deleted? i.e. https://github.com/empowerhack/DrawMyLife-Service/blob/master/app/models/user.rb#L10 - is this overkill?
- [ ] Retain link between Org and Photo through `Photo.user.organisation`, even if user has been made inactive

**Comment by rocioleon** [comment]
@stevesmith2609 
Well spotted! 
Also, when a user has uploaded a file so it is 'complete' which means it can be seen on the web campaigning tool. What would happen if for any reason after that, they need to edit it?? 
Would it be that file 'inactive' (and no visible on the web campaigning tool as well?)
