### ISSUE TITLE
Make the website responsive / mobile-friendly (initial phase)

### ISSUE THREAD

**Issue by krissy** [empowerhack/DrawMyLife-Service#54]
I've managed to complete an end-to-end photo upload on mobile (iPhone 6S), which is a big yay! This means functionally this workflow can work on a mobile device.

However, it's in desperate need of a responsive makeover as the process is fiddly and requires a lot of zooming in and dragging around for fields to be clickable/typeable. 

IMO we should discuss prioritizing at least making the form responsive for the pilot as Valentina mentioned convenience of phone uploads and scope out the key UI/frontend work across this and the tasks outlined in #50.

Thoughts @CathMollie @rocioleon @tanyapowell @stevesmith2609 @smurfyrach?

**Comment by CathMollie** [comment]
@krissy Agree - this is a good way of making the phone upload exp better. It won't block this pilot if it doesn't happen but would be good to try. @tanyapowell this is something we can scope out in our meeting on Tues.

**Comment by tanyapowell** [comment]
@CathMollie - The Bootstrap framework is already part of the project so can utilise it the best I can for the pilot and iterate following feedback from the pilot users. But yes, let's scope it out during Tuesday's meeting

**Comment by tanyapowell** [comment]
@rocioleon will you have capacity to create wireframes for a mobile/responsive version of the portal?

**Comment by rocioleon** [comment]
@tanyapowell yes we can do it but I cannot promise it will be done during this first milestone. 

@CathMollie,  as i suppose to give priority to the style guide for this milestone? Mobile was not included at first but I will be happy to do it indeed. 

I need you guys tell me what is more important for this Usability testing with Valentina.

**Comment by CathMollie** [comment]
@rocioleon Just discussed this with @stevesmith2609 and @tanyapowell - we will push to the next pilot.
