### ISSUE TITLE
Drawings Form: Fix Gender field

### ISSUE THREAD

**Issue by krissy** [empowerhack/DrawMyLife-Service#56]
- Currently defaulting to Male, should default to nil
- We should add another gender type "Other"
- Ideally these are enums also

**Comment by tanyapowell** [comment]
@rocioleon are these included on the wireframes?

**Comment by rocioleon** [comment]
@tanyapowell yes it is included on page 2 Add new drawing.
@krissy I agree with you, we should make it default 'other' (my mistake)

**Comment by tanyapowell** [comment]
@rocioleon are these colour co-ordinated square buttons? I can't really tell what they are 🙈

**Comment by steverabino** [comment]
Importantly, default to `nil`, not to "other"

**Comment by steverabino** [comment]
Was fixed in #78
