### ISSUE TITLE
Clean up / use good sass and styles in general

### ISSUE THREAD

**Issue by krissy** [empowerhack/DrawMyLife-Service#58]
The sass in https://github.com/empowerhack/DrawMyLife-Service/blob/master/app/assets/stylesheets/application.scss needs a lot of love. We need someone who's familiar with sass and latest frontend practices to clean this all up using good standards. Can potentially be picked up by someone external to the team and wanting to practice their sass as it's an isolated task.

**Comment by CathMollie** [comment]
@krissy Shall I put a call out to #help wanted?

**Comment by tanyapowell** [comment]
@krissy started cleaning up the SASS files last week. Will pull the latest changes and see what's the latest damage

**Comment by steverabino** [comment]
@tanyapowell Can this be closed now that #61 is merged, or is there more to do?

**Comment by tanyapowell** [comment]
@stevesmith2609 yep, closing now
