### ISSUE TITLE
Update Navbar Component/View to match wireframe

### ISSUE THREAD

**Issue by tanyapowell** [empowerhack/DrawMyLife-Service#62]
Navbar should be changed to this:
![image](https://cloud.githubusercontent.com/assets/11095605/17495447/fc9e2800-5db0-11e6-967d-79a35d62f2b4.png)
- Style guide to follow
### For the pilot
- `content management` is acting as the home page
- only branding (`Draw My Life`), `content management`, `upload` and user profile dropdown buttons should be included
- `content management` and `upload` should only appear **after** a user has signed in

**Comment by tanyapowell** [comment]
@rocioleon should `settings` be omitted from the pilot version of the portal. Not sure if it's needed for it? What do you think?

![image](https://cloud.githubusercontent.com/assets/11095605/17499514/a4f15284-5dc5-11e6-8b06-92faad362a65.png)

**Comment by rocioleon** [comment]
Yes, If this makes things easier and quicker for you, at this stage it is not mandatory as we are actually waiting for some information about this section.

**Comment by tanyapowell** [comment]
Thanks for confirming @rocioleon. Will leave it out for now 😄

**Comment by tanyapowell** [comment]
It was also confirmed during yesterday's team call to drop `organization` for the pilot and add it at a later stage

**Comment by EChesters** [comment]
Screenshot of the most up to date version of the navbar. I struggled with the separators to make them smaller, as well as the border around the email. This would require extra margin and possibly increase size of the navbar.

 I've missed out the settings and organisations as previously mentioned.

_Hover styling_
<img width="591" alt="screen shot 2016-08-10 at 22 14 37" src="https://cloud.githubusercontent.com/assets/2605703/17571382/dfee3a22-5f47-11e6-8250-d4c42cc66b19.png">

<img width="1680" alt="screen shot 2016-08-10 at 22 06 28" src="https://cloud.githubusercontent.com/assets/2605703/17571093/bbc04dc6-5f46-11e6-95bb-52c65ebcc3a3.png">

**Comment by tanyapowell** [comment]
done and dusted
