### ISSUE TITLE
Update Homepage to be a list view instead of a grid view

### ISSUE THREAD

**Issue by tanyapowell** [empowerhack/DrawMyLife-Service#64]
![image](https://cloud.githubusercontent.com/assets/11095605/17529730/615402c2-5e6c-11e6-8855-98b904f53354.png)

Using Bootstrap's table classes, convert the homepage into a list view to match the wireframe above

For the modal/popover on hovering over the thumbnail image Bootstrap.js is required

**Comment by tanyapowell** [comment]
@rocioleon just had a thought - how will the modal/pop up of the small preview image into a larger preview image look on a mobile device when a user hovers/clicks on it? 

At the moment the thumbnail size is 100px x 100px so the preview of the image is actually pretty good. 

###### How the thumbnail looks currently

![image](https://cloud.githubusercontent.com/assets/11095605/17598737/cf4e15c8-5ff3-11e6-86b1-afc34643ece9.png)

**Comment by rocioleon** [comment]
@tanyapowell 
sorry I missed this message but I see that you fixed it.

Thanks!
