### ISSUE TITLE
Update Upload page to match wireframe

### ISSUE THREAD

**Issue by tanyapowell** [empowerhack/DrawMyLife-Service#65]
![image](https://cloud.githubusercontent.com/assets/11095605/17530059/d51cacda-5e6d-11e6-97c9-a4d35bdce111.png)

**Comment by tanyapowell** [comment]
@rocioleon I'm a bit confused by the alert at the top. Do you want all fields to be required and filled in for a successful submission? The wording is confusing me

@krissy are all fields _currently_ set to required?

**Comment by krissy** [comment]
@tanyapowell this closed PR summarizes the rules re required fields https://github.com/empowerhack/DrawMyLife-Service/pull/55 - we'll be outlining these in business rules once they're set up too. Let me know if it doesn't make sense!

**Comment by rocioleon** [comment]
@tanyapowell and @krissy once again sorry for the delay to replay. I missed this message. I am not sure if this is now clear or you want to talk. Let me know. Thanks!
