### ISSUE TITLE
Add analytics

### ISSUE THREAD

**Issue by EChesters** [empowerhack/DrawMyLife-Service#68]
Basic analytics need to be added to the website
- Google Analytics
- HotJar
  The above two offer free accounts. Google Analytics for statistics on funnels, bounce rates etc. HotJar provides 200 recordings at a time for free, of users using the site. _Only the screen and mouse actions are recorded_

_TODO:_
- Set up accounts for both services
- Add tracking script to footer via partials (alongside JS)

_NOTES_
- Link for HotJar: http://drawmylife.herokuapp.com/

**Comment by EChesters** [comment]
Is there a communal email address which I can setup for the analytics? Otherwise it'll just be on my account which I can't share, and it's pointless. 

If so, could someone attach an email onto this issue?

**Comment by CathMollie** [comment]
@EChesters Can this now close?

**Comment by EChesters** [comment]
Not yet, just adding the Google Analytics now so we can close this 😄

**Comment by EChesters** [comment]
Done with commits mentioned above.
