### ISSUE TITLE
FIX: Password reset

### ISSUE THREAD

**Issue by krissy** [empowerhack/DrawMyLife-Service#79]
# What

The password reset functionality linked to the [Devise gem](https://github.com/plataformatec/devise/) is broken 💃 

We need to investigate and fix it :)

**Comment by krissy** [comment]
As part of this ticket, you might want to set up mailcatcher on your machines https://mailcatcher.me/ (scroll down for rails instructions). This will “catch” any emails you send locally and you can view them in your browser. This will help debug if the issue is local only or something to do with staging/production config

**Comment by krissy** [comment]
This issue has been addressed with the changes in https://github.com/empowerhack/DrawMyLife-Service/pull/135 - emails needed to be set up in general. cc @littlethao in case you still had this in progress!

**Comment by steverabino** [comment]
Done!
