### ISSUE TITLE
Add DP warnings to UI 

### ISSUE THREAD

**Issue by CathMollie** [empowerhack/DrawMyLife-Service#83]
There are two issues of consent: 
- consent from the child to collect the artwork 
- consent from the child to showcase the artwork 

@smurfyrach 's suggestions:
- Tickbox to indicate consent from child to collect artwork
- 'Yes/No' option to indicate consent from child to showcase artwork
- Link to end user licence with terms of use - may need legal input. @smurfyrach has offered to draft these.

Also consider: 
- Warning/reminder in UI to remove child's name from drawing. The likely path is that they'll remove name offline and re-upload the anonymized drawing?

**If picking this up at WHFNP hack night**
We need to add two indicators to show that consent has been given to collect artwork (see options below)
This should probably be positioned at the bottom of the 'Details of Artist' section, underneath 'Context/Story of Artist'

<img width="737" alt="screen shot 2016-10-06 at 20 09 04" src="https://cloud.githubusercontent.com/assets/20586372/19166822/0b58ef64-8c01-11e6-8e62-c824ce53f7e2.png">
- Yes/No option: Artist consents to collect and upload artwork
- Yes/No option: Artist consents to share artwork

**Comment by krissy** [comment]
What do we need to confirm the legal requirements discussed and confirm the need to do this? Considering existing drawings they want to upload and trying not to interrupt the organic interaction between field worker and child.
