### ISSUE TITLE
Set up Heroku staging environment

### ISSUE THREAD

**Issue by CathMollie** [empowerhack/DrawMyLife-Service#94]
Test new pages to push during pilot e.g.
- PDF uploading
- Changes to navbar (responsive work)

**Comment by steverabino** [comment]
Staging environment live at https://drawmylife-staging.herokuapp.com

Developers will need to:
1. Add local remote: `git remote add dml-staging https://git.heroku.com/drawmylife-staging.git`
2. Whenever you want to do any heroku commands, add which remote you want to use by adding `—remote dml-staging` to your command
